name: Release action

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build projects
        run: mvn -B package --file pom.xml

      - name: Copy artifact
        run: |
          mkdir app
          cp target/*.war app/currency-converter.war

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: currency-converter.war
          path: app/currency-converter.war

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifactFolder

      - name: Display structure of downloaded files
        run: ls -R artifactFolder

      - name: Create GitHub Release with the artifact
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          token: ${{ secrets.RELEASE_TOKEN }}
          artifacts: "artifactFolder/*.war"
